export enum ErrorCode {
  // Auth errors
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',

  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_ID = 'INVALID_ID',

  // Not found errors
  NOT_FOUND = 'NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  KID_NOT_FOUND = 'KID_NOT_FOUND',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  LOCATION_NOT_FOUND = 'LOCATION_NOT_FOUND',
  BANNER_NOT_FOUND = 'BANNER_NOT_FOUND',
  CODE_NOT_FOUND = 'CODE_NOT_FOUND',
  QUIZ_NOT_FOUND = 'QUIZ_NOT_FOUND',
  REPORT_NOT_FOUND = 'REPORT_NOT_FOUND',

  // Business logic errors
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  DUPLICATE_PHONE = 'DUPLICATE_PHONE',
  INVALID_SESSION_CAPACITY = 'INVALID_SESSION_CAPACITY',
  SESSION_FULL = 'SESSION_FULL',
  INVALID_DATE_RANGE = 'INVALID_DATE_RANGE',
  KID_REGISTRATION_INCOMPLETE = 'KID_REGISTRATION_INCOMPLETE',

  // Server errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
}
